// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chat.proto

#include "chat.pb.h"
#include "chat.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace chat {

static const char* ChatService_method_names[] = {
  "/chat.ChatService/Chat",
};

std::unique_ptr< ChatService::Stub> ChatService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChatService::Stub> stub(new ChatService::Stub(channel, options));
  return stub;
}

ChatService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Chat_(ChatService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::chat::ChatMessage, ::chat::ChatMessage>* ChatService::Stub::ChatRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::chat::ChatMessage, ::chat::ChatMessage>::Create(channel_.get(), rpcmethod_Chat_, context);
}

void ChatService::Stub::async::Chat(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::chat::ChatMessage,::chat::ChatMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::chat::ChatMessage,::chat::ChatMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_Chat_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::chat::ChatMessage, ::chat::ChatMessage>* ChatService::Stub::AsyncChatRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::chat::ChatMessage, ::chat::ChatMessage>::Create(channel_.get(), cq, rpcmethod_Chat_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::chat::ChatMessage, ::chat::ChatMessage>* ChatService::Stub::PrepareAsyncChatRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::chat::ChatMessage, ::chat::ChatMessage>::Create(channel_.get(), cq, rpcmethod_Chat_, context, false, nullptr);
}

ChatService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ChatService::Service, ::chat::ChatMessage, ::chat::ChatMessage>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::chat::ChatMessage,
             ::chat::ChatMessage>* stream) {
               return service->Chat(ctx, stream);
             }, this)));
}

ChatService::Service::~Service() {
}

::grpc::Status ChatService::Service::Chat(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::chat::ChatMessage, ::chat::ChatMessage>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace chat

